labslot/home/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'home'
# Moved urls to their respective apps
urlpatterns = [
    # /home/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # Lab URLs needed for detail view
    url(r'^labs/', include('labs.urls')),
    # /registration and login
    # url(r'^userformview/$', views.UserFormView.as_view(), name = 'register'),
    # /about/
    url(r'^aboutview/$', views.AboutView.as_view(), name='about'),

]

labslot/labs/urls.py
from django.conf.urls import url
from . import views

app_name = 'labs'

urlpatterns = [
    # /company/
    url(r'^company/create/$', views.CompanyCreateView.as_view(), name='company-add'),
    url(r'^company/update/(?P<pk>\d+)$', views.CompanyUpdateView.as_view(), name='company-update'),
    url(r'^company/delete/(?P<pk>\d+)$', views.CompanyDeleteView.as_view(), name='company-delete'),
    url(r'^company/detail/(?P<pk>\d+)$', views.CompanyDetailView.as_view(), name='company-detail'),
    url(r'^company/list/$', views.CompanyListView.as_view(), name='company-list'),

    # /labview/
    # url(r'^labview/$', views.LabView.as_view(), name='labview'),
    # # /lablistview/
    # url(r'^lablistview/$', views.LablistView.as_view, name='lablistview'),
    # # /detailview/
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # # /home/labs/add/
    # url(r'^labs/add/$', views.LabsCreate.as_view(), name='labs-add'),
    # # Update Labs
    # url(r'^(?P<pk>[0-9]+)/$', views.LabsUpdate.as_view(), name='labs-update'),
    # # Delete Labs
    # url(r'^(?P<pk>[0-9]+)/delete/$', views.LabsDelete.as_view(), name='labs-delete'),

    url(r'^create/', views.LabCreateView.as_view(), name='lab_add'),
    url(r'^list/$', views.LabListView.as_view(), name='lab_list'),
    url(r'^mylist/$', views.my_list, name='own_lab_list'),
    url(r'^details/(?P<pk>\d+)$', views.LabDetailView.as_view(), name='lab_detail'),
    url(r'^update/(?P<pk>\d+)$', views.LabUpdateView.as_view(), name='lab_update'),
    url(r'^delete/(?P<pk>\d+)$', views.LabDeleteView.as_view(), name='lab_delete'),

    url(r'^labfilter/$', views.MyList.as_view(), name='labfilter'),

    url(r'^(?P<lab_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

labslot/labslot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from booking.views import charge

urlpatterns = [
    url(r'^charge/(?P<pk>\d+)/$', charge, name='charge'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^labs/', include('labs.urls', namespace='labs')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^services/', include('services.urls')),
    url(r'^equipment/', include('equipment.urls')),
     url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/reset_my_password.html'}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name': 'registration/my_password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name': 'registration/my_password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name': 'registration/my_password_reset_complete.html'}, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labslot/labs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.contenttypes.fields import GenericRelation


class Company(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=150)
    company_address = models.CharField(max_length=250)
    company_website = models.URLField()
    company_industry = models.CharField(max_length=150)
    company_product_type = models.CharField(max_length=150)
    company_linked_in_profile = models.URLField()

    company_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.company_name


class Lab(models.Model):
    LAB_TYPE = (
        ('science', 'Science'),
        ('engineering', 'Engineering'),
    )

    TIME_PERIOD = (
        ('hour', 'Hour'),
        ('day', 'Day'),
        ('week', 'Week'),
        ('month', 'Month'),
    )

    company = models.ForeignKey(Company, verbose_name="Company Name", on_delete=models.CASCADE)
    name = models.CharField(max_length=500, help_text='Lab Title')
    lab_type = models.CharField(choices=LAB_TYPE, max_length=150, default='science')
    street_address = models.CharField(max_length=300, null=True)
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    details = models.TextField(help_text='Space, equipment and other facilities in the lab.', default='Stuff')
    contact_person = models.CharField(max_length=100, blank=True, null=True, help_text='Secondary Contact Person')
    contact_email = models.EmailField(max_length=100, blank=True, null=True, help_text='Secondary Contact Email')
    contact_phone = models.CharField(max_length=15)
    price = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10000)],
                                verbose_name="Lab Price",
                                help_text='Lab Price (in NZ dollars)')
    time_period = models.CharField(choices=TIME_PERIOD, max_length=50)
    image1 = models.ImageField(upload_to='labs/images/%Y/%m/%d', help_text=u'Upload Lab Image', blank=False,
                               null=False)
    image2 = models.ImageField(upload_to='labs/images/%Y/%m/%d', help_text=u'Upload Lab Image', blank=False,
                               null=False)
    image3 = models.ImageField(upload_to='labs/images/%Y/%m/%d', help_text=u'Upload Lab Image', blank=False,
                               null=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    publish = models.BooleanField(default=True)
    average_ratings = models.FloatField(
        validators=[MinValueValidator(1), MaxValueValidator(5)], null=True, blank=True)
    lab_equipments = models.TextField(max_length=100, blank=True, null=True)
    lab_requirements = models.TextField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('labs:detail', kwargs={'pk': self.pk})


class Activity(models.Model):
    lab = models.ForeignKey(Lab, verbose_name="favourite lab",
                            on_delete=models.CASCADE, related_name='favourite_lab')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_favourite')
    favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

labslot/labs/forms.py
from django import forms

from .models import Company, Lab


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ('owner', 'company_verified')


class LabForm(forms.ModelForm):
    # company = forms.CharField(max_length=20, widget=forms.TextInput(
    #     attrs={'readonly': 'readonly'}))
    extra_field_count = forms.CharField(widget=forms.HiddenInput())

    class Meta:
        model = Lab
        exclude = ('created_date', 'updated_date',
                   'publish', 'average_ratings')
        fields = (
        'company', 'name', 'lab_type', 'street_address', 'city', 'country', 'contact_person', 'contact_email', 'contact_phone', 'price',
        'time_period', 'lab_equipments', 'lab_requirements', 'image1', 'image2', 'image3')

    def __init__(self, *args, **kwargs):
        lab_equipments = kwargs.pop('extra', 0)

        super(LabForm, self).__init__(*args, **kwargs)
        self.fields['extra_field_count'].initial = lab_equipments

        for index in range(int(lab_equipments)):
            self.fields['extra_field_{index}'.format(index=index)] = forms.CharField()

labslot/labs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, View
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Company, Lab
from .forms import CompanyForm, LabForm
from django.db.models import Q
from labs.models import Lab, Activity
from .filters import LabFilter
from django_filters.views import FilterView
from django_filters.views import BaseFilterView
from django.contrib.auth.decorators import login_required
from review_ratings.forms import ReviewRatingForm
from review_ratings.models import ReviewRating
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden
from django.urls import reverse
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect
from review_ratings.models import ReviewRating
from django.contrib import messages
from labs.models import Company
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.shortcuts import render_to_response
from django.db.models import Avg


class CompanyListView(generic.ListView):
    model = Company
    context_object_name = 'companies'
    template_name = 'company/company_list.html'


class CompanyDetailView(generic.DetailView):
    model = Company
    context_object_name = 'company'
    template_name = 'company/company_detail.html'


class CompanyCreateView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'company/company_create.html'
    success_url = reverse_lazy('labs:company-list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CompanyCreateView, self).form_valid(form)


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'company/company_create.html'
    success_url = reverse_lazy('labs:company-list')


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    context_object_name = 'company'
    template_name = 'company/company_delete.html'
    success_url = reverse_lazy('labs:company-list')


# Lab Views starts from here....
def my_list(request):
    labs = Lab.objects.filter(company__owner=request.user)
    return render(request, 'labs/my_lab_list.html', {'labs': labs, })


class LabListView(generic.ListView):
    model = Lab
    context_object_name = 'labs'
    paginate_by = 10
    template_name = 'home/lab_listings.html'

    def get_queryset(self):
        return Lab.objects.filter(publish=True)


class LabDetailView(FormMixin, generic.DetailView):
    model = Lab
    context_object_name = 'lab'
    template_name = 'labs/detail.html'
    form_class = ReviewRatingForm

    def success_url(self):
        return reverse('labs:lab_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        lab = self.kwargs['pk']
        context = super(LabDetailView, self).get_context_data(**kwargs)
        obj = ReviewRating.objects.filter(lab=lab)
        avg = obj.aggregate(rating=Avg('rating'))
        average = avg['rating']
        lab = Lab.objects.get(id=lab)
        print(average)
        if average is None:
            average = 0
            lab.average_ratings = average
        else:
            average = round(average * 2) / 2
            lab.average_ratings = average
        lab.save()
        context.update({
            'reviews': ReviewRating.objects.filter(lab=lab)[:5],
            'average': average
        })
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        lab = self.kwargs['pk']
        form_post = Lab.objects.get(id=lab)
        if not request.user.is_authenticated:
            return HttpResponseForbidden
        self.object = self.get_object
        form = self.get_form()
        if form.is_valid():
            form.instance.user = self.request.user
            form.instance.lab = form_post

            form.save()
            return HttpResponseRedirect(self.request.path_info)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class LabCreateView(LoginRequiredMixin, CreateView):
    model = Lab
    form_class = LabForm
    template_name = 'labs/lab_create.html'
    success_url = reverse_lazy('labs:labfilter')

    def get(self, request, *args, **kwargs):
        user_pk = request.user.pk
        company = Company.objects.get(owner=request.user)
        self.initial['company'] = company.company_name
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        user = request.user
        company = Company.objects.get(owner=user)
        print("company", company)
        if company.company_verified:
            form = self.get_form()
            if form.is_valid():
                form_company = form.cleaned_data['company']
                print(form_company)
                if company == form_company:
                    form.save()
                    return self.form_valid(form)
                else:
                    messages.error(request, 'The Company You entered is not your company')
                    return render(request, self.template_name, {'form': form})


            else:
                return render(request, self.template_name, {'form': form})
        else:
            form = self.get_form()
            messages.error(request, 'Your Company has not been verified')
            return render(request, self.template_name, {'form': form})


class LabUpdateView(LoginRequiredMixin, UpdateView):
    model = Lab
    form_class = LabForm
    template_name = 'labs/lab_create.html'
    success_url = reverse_lazy('labs:lab_list')


class LabDeleteView(LoginRequiredMixin, DeleteView):
    model = Lab
    context_object_name = 'lab'
    template_name = 'labs/lab_delete.html'
    success_url = reverse_lazy('labs:lab_list')


class MyList(BaseFilterView, generic.ListView):
    model = Lab
    template_name = 'search/labs_filter.html'
    context_object_name = 'filters'
    filterset_class = LabFilter
    strict = False
    paginate_by = 4

    def get_queryset(self):
        queryset = Lab.objects.filter(publish=True).order_by('-id')
        return queryset


def favorite(request, lab_id):
    lab = get_object_or_404(Lab, pk=lab_id)
    print(lab)
    try:
        favorite = Activity.objects.create(
            lab=lab, user=request.user, favorite=True)
        favorite.save()
    except(KeyError, Lab.DoesNotExist):
        return render(request, 'labs/detail.html', {
            'lab': lab,
            'error_message': 'Invalid request'
        })

    return render(request, 'labs/detail.html', {'lab': lab, 'favorite': favorite})

labslot/labs/templates/company/company_create.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %}{% trans 'Add Company' %}{% endblock %}
{% block index %}
<div class="container">
   <div class="page-content" style="padding:30px">
    <div class="row">
        <div class="col-md-2">
            {% include 'profile/partial_settings_menu.html' with active='Add Company' %}
        </div>
        <div class="col-md-9">
            <form role="form" class="form-horizontal" method="post">
            	{{ form.as_p }}
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="tg-btn">{% trans 'Save' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock index %}

labslot/labs/templates/company/company_delete.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %}{% trans 'Account Settings' %}{% endblock %}
{% block index %}
<div class="container">
    <div class="page-content" style="padding:30px">
        <div class="row">
            <div class="col-md-2">
                {% include 'profile/partial_settings_menu.html' with active='company' %}
            </div>

<center><form method="post">
	{% csrf_token %}
	<h3> Are you sure want to delete "{{ company }}"</h3>
	<input type="submit" value="Confirm" class="tg-btn" style="background-color: rgb(93, 197, 96);border:rgb(93,197,96);
">
</form></center>
        </div>
    </div>
</div>
{% endblock index %}

labslot/labs/templates/company/company_detail.html
<center><b><u><h1>COMPANY DETAIL</h1></u></b>
<h1>Name: {{company.name}}</h1>
<h1>Description: {{company.description}}</h1></center>

labslot/labs/templates/company/company_list.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load i18n %}
{% block title %}{% trans 'Account Settings' %}{% endblock %}
{% block index %}
<div class="container">
    <div class="page-content" style="padding:30px">
        <div class="row">
            <div class="col-md-2">
                {% include 'profile/partial_settings_menu.html' with active='company' %}
            </div>
            <div class="col-md-9">
                <div class="tg-latestserviceproviders">
                    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4">
                        {% for company in companies %}
                        {% if company.owner.is_authenticated and company.owner == request.user %}
                        <div class="tg-serviceprovider tg-automotive">
                            <figure class="tg-featuredimg" href="#">
                                <img src="{% static 'images/serviceproviders/img-01.jpg' %}"
                                             alt="image description">
                                <figcaption>
                                    <a class="tg-themetag tg-categorytag"
                                               href="javascript:void(0);">{{ lab.type }}</a>
                                    <a class="tg-heart tg-liked" href="javascript:void(0);"><i
                                                    class="fa fa-heart"></i></a>
                                </figcaption>
                            </figure>
                            <div class="tg-serviceprovidercontent">
                                {% comment %}
                                <div class="tg-companylogo"><a href="#"><img
                                                src="{% static 'images/logos/img-01.png' %}"
                                                alt="image description"></a></div>
                                {% endcomment %}
                                <div class="tg-companycontent">
                                    <ul class="tg-tags">
                                        <li><a class="tg-tag tg-featuredtag" href="#">featured</a></li>
                                        <li><a class="tg-tag tg-verifiedtag" href="#">verified</a></li>
                                    </ul>
                                    <div class="tg-title">
                                        <h2><a href="#">Name:{{ company.company_name}}</a></h2>
                                        <h3>Address:{{ company.company_address}}</h3><br>
                                        <h3>Status:{{ company.company_verified}}</h3><br>
                                        <a href="{% url 'labs:company-update' company.pk %}"><i class="fa fa-edit fa-2x" title="update"></i></a>&nbsp;
                                        <a href="{% url 'labs:company-delete' company.pk %}" class="js-delete-book"><i class="fa fa-trash fa-2x" title="delete" aria-hidden="true"></i></a>
                                    </div>
                                    <ul class="tg-matadata">
                                        <li><span class="tg-stars"><span></span></span></li>
                                        <li>
                                            <i class="fa fa-thumbs-o-up"></i>
                                            <em>99% (1009 votes)</em>
                                        </li>
                                    </ul>
                                    <hr><br>
                                    {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock index %}