labslot/booking/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from booking import views
urlpatterns=[
	url(r'^book/(?P<pk>\d+)$', views.ReservationView.as_view(), name='book'),
	url(r'^request/list/$', views.booking_list, name='booking_lab_list'),
	url(r'^mybooking/list/$', views.my_booking_list, name='my_booking_lab_list'),
	url(r'^details/(?P<pk>\d+)$', views.BookingDetail.as_view(), name='booking_detail'),
	url(r'^status/(?P<pk>\d+)$', views.BookingStatusView.as_view(), name='booking_accept'),
]

labslot/home/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'home'
# Moved urls to their respective apps
urlpatterns = [
    # /home/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # Lab URLs needed for detail view
    url(r'^labs/', include('labs.urls')),
    # /registration and login
    # url(r'^userformview/$', views.UserFormView.as_view(), name = 'register'),
    # /about/
    url(r'^aboutview/$', views.AboutView.as_view(), name='about'),

]

labslot/labslot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from booking.views import charge

urlpatterns = [
    url(r'^charge/(?P<pk>\d+)/$', charge, name='charge'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^labs/', include('labs.urls', namespace='labs')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^services/', include('services.urls')),
    url(r'^equipment/', include('equipment.urls')),
     url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/reset_my_password.html'}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name': 'registration/my_password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name': 'registration/my_password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name': 'registration/my_password_reset_complete.html'}, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labslot/booking/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from labs.models import Lab
from django.contrib.auth import get_user_model

User = get_user_model()  # Create a Reservation Model which stores booking details


class Reservation(models.Model):
    STATUS = (
        ('Requested', "Requested"),
        ('Accepted', "Accepted"),
        ('Denied', "Denied"),
    )
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    username = models.CharField(max_length=255)
    CheckInDate = models.DateField()
    CheckOutDate = models.DateField()
    CheckInTime = models.TimeField()
    CheckOutTime = models.TimeField()
    message = models.TextField()
    status = models.CharField(choices=STATUS, default='Requested', max_length=50)

    class Meta:
        verbose_name_plural = 'Reservation'

    def __str__(self):
        return 'reservation.id {}-applicant.username '.format(self.id, self.username)

labslot/booking/forms.py
from django import forms
from .models import Reservation


class ReservationForm(forms.ModelForm):
    price = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'readonly': 'readonly'}))
    username = forms.CharField(max_length=20, widget=forms.TextInput(
        attrs={'readonly': 'readonly'}))    

    class Meta:
        model = Reservation
        fields = ('lab', 'price','username','CheckInDate', 'CheckOutDate', 'CheckInTime', 'CheckOutTime', 'message')


class BookingStatusForm(forms.ModelForm):
	class Meta:
		model = Reservation
		fields = ('status',)

labslot/booking/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from datetime import datetime, timedelta
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
import json
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseBadRequest
from django.template.loader import render_to_string
from django.views.generic import TemplateView, FormView, UpdateView
from django.views.generic.edit import CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count, Sum
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from labs.models import Lab
from .models import Reservation
from .forms import ReservationForm, BookingStatusForm
from .models import Reservation
from django.views.generic import View
from django.shortcuts import get_object_or_404
from django.forms.models import model_to_dict
from authentication.models import User
from django.conf import settings
import stripe  # new

stripe.api_key = settings.STRIPE_SECRET_KEY  # new


# Create your views here.
class ReservationView(SuccessMessageMixin, FormView):
    template_name = 'lab_book_modal.html'
    initial = {}
    form_class = ReservationForm
    success_url = '/thanks/'
    success_message = 'Lab has been successfully booked.'
    data = dict()

    def get(self, request, *args, **kwargs):
        user_pk = request.user.pk
        user1 = User.objects.get(pk=user_pk)
        self.initial['lab'] = Lab.objects.get(pk=kwargs.get('pk'))
        self.initial['username'] = user1.username
        self.initial['type'] = Lab.objects.get(pk=kwargs.get('pk')).lab_type
        self.initial['price'] = Lab.objects.get(pk=kwargs.get('pk')).price
        print(self.initial['type'])
        form = self.form_class(initial=self.initial)
        self.data['html_form'] = render_to_string(self.template_name, {'form': form}, request=request)
        return JsonResponse(self.data)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            if request.user.is_authenticated:
                instance.user = request.user
            instance.save()
            self.data['form_is_valid'] = True
            return JsonResponse(self.data)
        else:
            self.data['form_is_valid'] = False
            self.data['html_form'] = render_to_string(self.template_name, {'form': form}, request=request)
        return JsonResponse(self.data)


def booking_list(request):
    booking_lab = Reservation.objects.filter(lab__company__owner=request.user).order_by('-id')
    key = settings.STRIPE_PUBLISHABLE_KEY
    return render(request, 'booking_list.html', {'booking_labs': booking_lab, 'key': key})


def my_booking_list(request):
    booking_lab = Reservation.objects.filter(username=request.user.username).order_by('-id')
    key = settings.STRIPE_PUBLISHABLE_KEY
    print(booking_lab)
    return render(request, 'my_booking_list.html', {'booking_labs': booking_lab, 'key': key})


"""
class MyBookingsView(ListView):
    def get(self,request ,pk):
        booking_lab = Reservation.objects.filter(username=request.user.username).order_by('-id')
        key = settings.STRIPE_PUBLISHABLE_KEY
        print(booking_lab)
        return render(request, 'my_booking_list.html', {'booking_labs': booking_lab, 'key': key})
"""


class BookingDetail(View):
    def get(self, request, pk):
        lab = get_object_or_404(Reservation, pk=pk)
        data = dict()
        data['lab'] = model_to_dict(lab)
        return JsonResponse(data)


class BookingStatusView(LoginRequiredMixin, UpdateView):
    model = Reservation
    form_class = BookingStatusForm
    template_name = 'booking_accept.html'
    success_url = reverse_lazy('booking:booking_lab_list')


class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['key'] = settings.STRIPE_PUBLISHABLE_KEY
        return context


def charge(request, pk):
    print(pk)
    reservation = Reservation.objects.get(id=pk)
    lab = Lab.objects.get(id=reservation.lab.id)
    amount = lab.price
    print(lab)
    if request.method == 'POST':
        charge = stripe.Charge.create(
            amount=amount,
            currency='usd',
            description='A Django charge',
            source=request.POST['stripeToken']
        )
        return render(request, 'charge.html', {'amount': amount})

# from django.urls import reverse_lazy
# from django.contrib.messages.views import SuccessMessageMixin
# from django.views import generic
# from django.http import HttpResponseForbidden

# class ChargeView(SuccessMessageMixin,generic.DetailView):
#     success_url = '/success/'
#     success_message = "Payment Successfully Done"
#     template_name = 'my_booking_list.html'

#     def get_context_data(self, **kwargs):
#         context = super(ChargeView).get_context_data(**kwargs)
#         context['key'] = settings.STRIPE_PUBLISHABLE_KEY
#         return context

#     def post(self, request, *args, **kwargs):
#         lab = self.kwargs['pk']
#         amount = lab.amount
#         print(lab)
#         charge = stripe.Charge.create(
#             amount=amount,
#             currency='usd',
#             description='A Django charge',
#             source=request.POST['stripeToken']
#         )
#         return HttpResponseRedirect(self.request.path_info)

#     def get_success_url(self):
#         success_url = reverse_lazy('charge', {'id': self.object.pk})
#         return success_url

labslot/booking/templates/booking_accept.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block index %}
    <!--************************************
        Inner Page Banner Start
*************************************-->
    
    <!--************************************
            Inner Page Banner End
    *************************************-->
        <!--************************************
                Login Register Start
        *************************************-->
        <div class="tg-main-section tg-haslayout">
            <div class="container">
                <div class="row">
                    <div id="tg-content" class="tg-content">
                        <form class="tg-themeform tg-formlogin-register" action="" method="post"
                              enctype="multipart/form-data">
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                                <div class="tg-heading">
                                    {{ form.as_p}}
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-10">
                                            <button class="tg-btn tg-btn-sm" type="submit">Save</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!--************************************
                Login Register End
        *************************************-->
    <!--************************************
				Main Start
		************************************
		<main id="tg-main" class="tg-main tg-paddingzero tg-haslayout">
			<!--************************************
					Login Register Start
			*************************************
			<div class="tg-main-section tg-haslayout">
				<div class="container">
					<div class="row">
						<div id="tg-content" class="tg-content">
							<form class="tg-themeform tg-formlogin-register">
								<div class="col-xs-12 col-sm-8 col-md-8 col-lg-12">
									<div class="tg-heading">
										<h2>Create a Listing</h2>
									</div>
                                    <form method="post">
									<fieldset>
										<ul class="tg-tabnav" role="tablist">
											<li role="presentation" class="active">
												<a href="#regularuser" data-toggle="tab">
													<span class="lnr lnr-user"></span>
													<div class="tg-navcontent">
														<h3>Add a Lab</h3>
														<span>Add a lab here</span>
													</div>
												</a>
											</li>
											<li role="presentation">
												<a href="#company" data-toggle="tab">
													<span class="lnr lnr-briefcase"></span>
													<div class="tg-navcontent">
														<h3>Add a Service or Equipment</h3>
														<span>Add a Service or equimpent here</span>
													</div>
												</a>
											</li>
										</ul>
										<div class="tg-themetabcontent tab-content">
											<div class="tab-pane active fade in" id="regularuser">
												<div class="form-group">
												</div>
												<div class="form-group">
													<input type="text" name="text" class="form-control" placeholder="Your Name">
												</div>
                                                <div class="form-group">
													<input type="text" name="text" class="form-control" placeholder="Company">
												</div>
												<div class="form-group">
													<input type="text" name="text" class="form-control" placeholder="Mobile">
												</div>
												<div class="form-group">
													<input type="email" name="email" class="form-control" placeholder="Email">
												</div>
												<div class="form-group">
													<input type="password" name="password" class="form-control" placeholder="Password">
												</div>
												<div class="form-group">
													<input type="password" name="retype-password" class="form-control" placeholder="Retype Password">
												</div>
												<div class="form-group">
													<img src="{%  static 'images/placeholder/img-02.png' %}" alt="image description">
												</div>
												<div class="form-group">
													<div class="tg-checkbox">
														<input type="checkbox" id="terms">
														<label for="terms">I have read the <a href="#">Terms &amp; Conditions</a> and accept them</label>
													</div>
												</div>
												<button class="tg-btn" type="submit">Register Now</button>
												<ul class="tg-socialicons tg-socialsharewithtext">
													<li class="tg-facebook">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-facebook-f"></i>
																<span>facebook</span>
															</em>
														</a>
													</li>
													<li class="tg-twitter">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-twitter"></i>
																<span>twitter</span>
															</em>
														</a>
													</li>
													<li class="tg-linkedin">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-linkedin"></i>
																<span>linkdin</span>
															</em>
														</a>
													</li>
													<li class="tg-googleplus">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-google-plus"></i>
																<span>googl+</span>
															</em>
														</a>
													</li>
													<li class="tg-tumblr">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-tumblr"></i>
																<span>tumblr</span>
															</em>
														</a>
													</li>
													<li class="tg-vimeo">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-vimeo"></i>
																<span>vimeo</span>
															</em>
														</a>
													</li>
												</ul>
											</div>
											<div class="tab-pane fade in" id="company">
												<div class="form-group">
													<div class="tg-registeras">
														<span>Register As:</span>
														<div class="tg-radio">
															<input type="radio" id="business" name="register" checked>
															<label for="business">Business</label>
														</div>
														<div class="tg-radio">
															<input type="radio" id="professional" name="register">
															<label for="professional">service manager</label>
														</div>
													</div>
												</div>
                                                <div>
                                                  {% csrf_token %}
                                                     {{ form.as_p }}
                                                <h3>Subscriptions Available</h3>
                                                </div>
												<div class="form-group">
													<img src="{% static 'images/placeholder/img-02.png' %}" alt="image description">
												</div>
												<div class="form-group">
													<div class="tg-checkbox">
														<input type="checkbox" id="conditions">
														<label for="conditions">I have read the <a href="#">Terms &amp; Conditions</a> and accept them</label>
													</div>
												</div>
												<button class="tg-btn" type="submit">Register Now</button>
												<ul class="tg-socialicons tg-socialsharewithtext">
													<li class="tg-facebook">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-facebook-f"></i>
																<span>facebook</span>
															</em>
														</a>
													</li>
													<li class="tg-twitter">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-twitter"></i>
																<span>twitter</span>
															</em>
														</a>
													</li>
													<li class="tg-linkedin">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-linkedin"></i>
																<span>linkdin</span>
															</em>
														</a>
													</li>
													<li class="tg-googleplus">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-google-plus"></i>
																<span>googl+</span>
															</em>
														</a>
													</li>
													<li class="tg-tumblr">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-tumblr"></i>
																<span>tumblr</span>
															</em>
														</a>
													</li>
													<li class="tg-vimeo">
														<a class="tg-roundicontext" href="javascript:void(0);">
															<em class="tg-usericonholder">
																<i class="fa fa-vimeo"></i>
																<span>vimeo</span>
															</em>
														</a>
													</li>
												</ul>
											</div>
										</div>
									</fieldset>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<!--************************************
					Login Register End
			*************************************-->
{% endblock %}

labslot/booking/templates/booking_list.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block index %}
{% if booking_labs %}
<main id="tg-main" class="tg-main tg-haslayout">
    <div class="container" >
        <div class="row">
            <div id="tg-twocolumns" class="tg-twocolumns">
                <div class="col-xs-12 ">
                    <div id="tg-content" class="tg-content">
                        <div class="tg-dashboard tg-dashboardappointmentsetting">
                            <form class="tg-themeform">
                                <fieldset>
                                    <div class="tg-dashboardbox tg-dashboardappointments">
                                        <div class="tg-dashboardtitle">
                                            <h2>Your Booking Requests</h2>
                                        </div>
                                        <div id="tg-datepicker" class="tg-datepicker"></div>
                                        <div class="tg-sortfilters">
                                            <div class="tg-sortfilter tg-sortby">
                                                <span>Sort By:</span>
                                                <div class="tg-select">
                                                    <select>
                                                        <option>days</option>
                                                        <option>Type</option>
                                                        <option>date</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="tg-sortfilter tg-arrange">
                                                <span>Arrange:</span>
                                                <div class="tg-select">
                                                    <select>
                                                        <option>des</option>
                                                        <option>Asc</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="tg-sortfilter tg-show">
                                                <span>Show:</span>
                                                <div class="tg-select">
                                                    <select>
                                                        <option>All</option>
                                                        <option>24</option>
                                                        <option>all</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        {% if booking_labs %}
                                        {% for lab in booking_labs %}
                                        <div class="tg-dashboardappointmentbox">
                                            <div class="tg-dashboardappointment">
                                                <div class="tg-servicetitle">
                                                    <figure>
                                                        <img src="{{lab.lab.image.url}}" alt="image description">
                                                    </figure>
                                                    <div class="tg-clientcontent">
                                                        <h2>{{lab.applicant_first_name}} {{lab.applicant_last_name}}</h2>
                                                        <span>Contact: {{lab.applicants_phone}}</span>
                                                    </div>
                                                </div>
                                                <div class="tg-serviceandservicetype">
                                                    <h3>Lab</h3>
                                                    <span>{{lab.lab.name}}</span>
                                                    <span>Type:{{lab.lab.lab_type}}</span>
                                                </div>
                                                <div class="tg-serviceandservicetype">
                                                    <h3>Booking Details</h3>
                                                    <span>From:&nbsp;{{lab.CheckInDate}} {{lab.CheckInTime}}</span>
                                                    <span>To:&nbsp;{{lab.CheckOutDate}} {{lab.CheckOutTime}}</span>
                                                </div>
                                                <div class="tg-serviceandservicetype">
                                                    <h3>Booking Status</h3>
                                                    {% if lab.status == 'Accepted' %}
                                                    <p class="bg-success">{{lab.status}}</p>
                                                    {% elif lab.status == 'Requested' %}
                                                    <p class="bg-warning">{{lab.status}}</p>
                                                    {% elif lab.status == 'Denied' %}
                                                    <p class="bg-danger">{{lab.status}}</p>
                                                    {% endif %}
                                                </div>
                                                <div class="tg-serviceandservicetype">
                                                    <div class="modal fade" id="exampleModalLong{{lab.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                                                        <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title" id="exampleModalLongTitle">Booking Request For {{lab.lab.name}}</h5>
                                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <div class="modal-body">
                                                                    <h3>{{lab.message}}</h3>
                                                                </div>
                                                                <div class="modal-footer">
                                                                    <button type="button" class="btn btn-primary" data-dismiss="modal" style="background: #5dc560;border-color:#5dc560;">Close</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong{{lab.id}}" style="background: #5dc560;border-color:#5dc560;">
                                                        View Message
                                                    </button>
                                                </div>
                                                <div class="tg-serviceandservicetype">
                                                    <h3>Action</h3>
                                                    {% if lab.status == 'Accepted' %}
                                                    <i class="fa fa-check" title="accepted"></i>
                                                    {% elif lab.status == 'Denied' %}
                                                    <i class="fa fa-ban " title="Reject" aria-hidden="true"></i>
                                                    {% elif lab.status == 'Requested' %}
                                                    <a href="{% url 'booking:booking_accept' lab.pk %}"><i class="fa fa-edit " title="Change Status" aria-hidden="true"></i></a>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        {% endif %}
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% else %}
<center>
    <h3>No booking requests to show</h3>
</center>
{% endif %}
{% endblock index %}

labslot/booking/templates/charge.html
<h2>Thanks, you paid <strong>{{amount}}</strong>!</h2>

labslot/booking/templates/lab_book.html
{% load static %}
{% load widget_tweaks %}
<!-- <h2 style="text-align: center;">COMING SOON!!!</h2>
 -->
{% for field in form %}
<div class="content">
    <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
        <p class="help-block">{{ error }}</p>
        {% endfor %}
    </div>
    {% endfor %}

labslot/booking/templates/lab_book_modal.html
<head>
  <script>
  $( function() {
    $( "#id_CheckInDate" ).datepicker({
            dateFormat:'yy-mm-dd'
        });
    
  } );
  </script>
  <script>
  $( function() {
    $( "#id_CheckOutDate" ).datepicker({
            dateFormat:'yy-mm-dd'
        });
    
  } );
  </script>
</head>
<form method="post" action="{% url 'booking:book' 1  %}" class="js-order-pleced"  >
  {% csrf_token %}
  <div class="modal-header" >
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <div>
   <div class="box" >
   <div class="content">
    <h4 class="modal-title" ></h4>
  </div>
  <div class="modal-body" >
    {{form}} 
    <br><br>
    <button type="submit" class="btn tg-btn">Confirm Booking</button>
    <button type="button" class="btn tg-btn" data-dismiss="modal">Close</button>
  </div>
  <div class="modal-footer">
 {#  <button type="submit" class="btn tg-btn">Confirm Booking</button> #}
  </div>
</form>