labslot/authentication/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from authentication import views
from labslot.decorators import anonymous_required

urlpatterns = [
    url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^signup/$',anonymous_required(views.UserSignupForm.as_view()), name='signup'),
	url(r'^login/$', anonymous_required(auth_views.login), {'template_name': 'registration/login_form.html'}, name='login'),
]

labslot/home/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'home'
# Moved urls to their respective apps
urlpatterns = [
    # /home/
    url(r'^$', views.IndexView.as_view(), name = 'index'),
    # Lab URLs needed for detail view
    url(r'^labs/', include('labs.urls')),
    # /registration and login
    # url(r'^userformview/$', views.UserFormView.as_view(), name = 'register'),
    # /about/
    url(r'^aboutview/$', views.AboutView.as_view(), name='about'),

]

labslot/labs/urls.py
from django.conf.urls import url
from . import views

app_name = 'labs'

urlpatterns = [
    # /company/
    url(r'^company/create/$', views.CompanyCreateView.as_view(), name='company-add'),
    url(r'^company/update/(?P<pk>\d+)$', views.CompanyUpdateView.as_view(), name='company-update'),
    url(r'^company/delete/(?P<pk>\d+)$', views.CompanyDeleteView.as_view(), name='company-delete'),
    url(r'^company/detail/(?P<pk>\d+)$', views.CompanyDetailView.as_view(), name='company-detail'),
    url(r'^company/list/$', views.CompanyListView.as_view(), name='company-list'),

    # /labview/
    # url(r'^labview/$', views.LabView.as_view(), name='labview'),
    # # /lablistview/
    # url(r'^lablistview/$', views.LablistView.as_view, name='lablistview'),
    # # /detailview/
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # # /home/labs/add/
    # url(r'^labs/add/$', views.LabsCreate.as_view(), name='labs-add'),
    # # Update Labs
    # url(r'^(?P<pk>[0-9]+)/$', views.LabsUpdate.as_view(), name='labs-update'),
    # # Delete Labs
    # url(r'^(?P<pk>[0-9]+)/delete/$', views.LabsDelete.as_view(), name='labs-delete'),

    url(r'^create/', views.LabCreateView.as_view(), name='lab_add'),
    url(r'^list/$', views.LabListView.as_view(), name='lab_list'),
    url(r'^mylist/$', views.my_list, name='own_lab_list'),
    url(r'^details/(?P<pk>\d+)$', views.LabDetailView.as_view(), name='lab_detail'),
    url(r'^update/(?P<pk>\d+)$', views.LabUpdateView.as_view(), name='lab_update'),
    url(r'^delete/(?P<pk>\d+)$', views.LabDeleteView.as_view(), name='lab_delete'),

    url(r'^labfilter/$', views.MyList.as_view(), name='labfilter'),

    url(r'^(?P<lab_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

labslot/labslot/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from booking.views import charge

urlpatterns = [
    url(r'^charge/(?P<pk>\d+)/$', charge, name='charge'),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^userprofile/', include('userprofile.urls', namespace='userprofile')),
    url(r'^labs/', include('labs.urls', namespace='labs')),
    url(r'^booking/', include('booking.urls', namespace='booking')),
    url(r'^services/', include('services.urls')),
    url(r'^equipment/', include('equipment.urls')),
     url(r'^password_reset/$', auth_views.password_reset, {'template_name': 'registration/reset_my_password.html'}, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done,{'template_name': 'registration/my_password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,{'template_name': 'registration/my_password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete,{'template_name': 'registration/my_password_reset_complete.html'}, name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labslot/userprofile/urls.py
from django.conf import settings
from django.conf.urls import url
from userprofile import views

urlpatterns = [
    url(r'^settings/$', views.settings, name='profilesettings'),
    url(r'^password-change/$', views.password, name='password'),
    url(r'^settings/picture/$', views.picture, name='picture'),
    url(r'^settings/upload_picture/$', views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', views.save_uploaded_picture,
        name='save_uploaded_picture'),


]

labslot/userprofile/models.py
from __future__ import unicode_literals
import hashlib
import os.path
import urllib
from django.conf import settings
from authentication.models import User
from django.db import models
from django.db.models.signals import post_save
from django.utils.encoding import python_2_unicode_compatible

GENDER = (
        ('Male', 'Male'),
        ('Female','Female'),
    )


python_2_unicode_compatible
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    company = models.CharField(max_length=50, null=True, blank=True)
    job_title = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=10,choices= GENDER, null=True, blank= True)
    phone = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
    	return "user:{}".format(self.user.first_name)

    def get_picture(self):
        picture=User.objects.all()
        no_picture = 'http://trybootcamp.vitorfs.com/static/img/user.png'
        try:
            filename = settings.MEDIA_ROOT + '/profile_pictures/' +\
                self.user.username + '.jpg'
            picture_url = settings.MEDIA_URL + 'profile_pictures/' +\
                self.user.username + '.jpg'
            if os.path.isfile(filename):
                return picture_url
            else:
                gravatar_url = 'http://www.gravatar.com/avatar/{0}?{1}'.format(
                    hashlib.md5(self.user.email.lower()).hexdigest(),
                    urllib.urlencode({'d': no_picture, 's': '256'})
                    )
                return gravatar_url

        except Exception:
            return no_picture

    def get_screen_name(self):
        try:
            if self.user.get_full_name():
                return self.user.get_full_name()
            else:
                return self.user.username
        except:
            return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance,first_name=instance.first_name,last_name=instance.first_name,email=instance.email)


def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

labslot/userprofile/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()
GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
)


class ProfileForm(forms.ModelForm):

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': "text", 'class': 'form-control'}),
        max_length=30,
        required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': "text", 'class': 'form-control'}),
        max_length=30,
        required=False)
    job_title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': "text", 'class': 'form-control'}),
        max_length=50,
        required=False)
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': "text", 'class': 'form-control'}),
        max_length=75,
        required=False)
    company = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': "text", 'class': 'form-control'}),
        max_length=50,
        required=False)
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control',
                                      'type': "text", 'class': 'form-control'}),
        max_length=50,
        required=False)

    gender = forms.ChoiceField(choices=GENDER)
    phone = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'class': 'control-label',
                                      'type': "text", 'class': 'form-control', }),
        max_length=50,
        required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'job_title',
                  'location', 'company', 'phone', 'email', 'gender']


class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Old password",
        required=True)

    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New password",
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm new password",
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        id = self.cleaned_data.get('id')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                'Old password don\'t match'])
        if new_password and new_password != confirm_password:
            self._errors['new_password'] = self.error_class([
                'Passwords don\'t match'])
        return self.cleaned_data

labslot/userprofile/views.py
import os
from django.urls import reverse
from django.conf import settings as django_settings
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden
from authentication.models import User
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.http import HttpResponseRedirect
from .forms import ProfileForm, ChangePasswordForm
from .models import Profile
from PIL import Image
from labs.models import Company

@login_required
def profile(request, username):
    profile = get_object_or_404(User, username=username)
    return render(request, 'profile/userprofile.html', {
        'profile': profile,

    })

@login_required
def settings(request):
    user = request.user
    company = Company.objects.get(owner=user)
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.profile.job_title = form.cleaned_data.get('job_title')
            user.email = form.cleaned_data.get('email')
            user.profile.company = form.cleaned_data.get('company')
            user.profile.location = form.cleaned_data.get('location')
            user.profile.gender = form.cleaned_data.get('gender')
            user.profile.phone = form.cleaned_data.get('phone')
            user.save()
            return redirect('/')

    else:
        form = ProfileForm(instance=user, initial={
            'user': request.user,
            'first_name':user.first_name,
            'last_name': user.last_name,
            'email':user.email,
            'job_title': user.profile.job_title,
            'company': company.company_name,
            'location': user.profile.location,
            'gender': user.profile.gender,
            'phone': user.profile.phone,

        })
    return render(request, 'profile/user.html', {'form': form})


@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('userprofile:profilesettings')

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'profile/password.html', {'form': form})


@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET.get('upload_picture') == 'uploaded':
            uploaded_picture = True

    except Exception:
        pass

    return render(request, 'profile/picture.html',
                  {'uploaded_picture': uploaded_picture})


@login_required
def upload_picture(request):
    try:
        profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
        if not os.path.exists(profile_pictures):
            os.makedirs(profile_pictures)
        f = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 350:
            new_width = 350
            new_height = (height * 350) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/userprofile/settings/picture/?upload_picture=uploaded')

    except Exception as e:
        print(e)
        return redirect('/userprofile/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w + x, h + y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)

    except Exception:
        pass

    return redirect('/userprofile/settings/')

labslot/userprofile/templates/profile/partial_settings_menu.html
{% load i18n %}
<div class="list-group">
    <a href="{% url 'userprofile:profilesettings' %}" class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Profile' %}</a>
    <a href="{% url 'userprofile:password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
    {%comment %}<a href="{% url 'labs:company-add' %}" class="list-group-item{% if active == 'Add Company' %} active{% endif %}">{% trans 'Add Company' %}</a>{% endcomment %}
    <a href="{% url 'labs:company-list' %}" class="list-group-item{% if active == 'company' %} active{% endif %}">{% trans 'Company' %}</a>
</div>

labslot/userprofile/templates/profile/password.html
{% extends 'home/base.html' %}
{% load i18n %}
{% block title %}{% trans 'Account Settings' %}{% endblock %}
{% block index %}
<div class="container">
   <div class="page-content" style="padding:30px">
    <div class="row">
        <div class="col-md-2">
            {% include 'profile/partial_settings_menu.html' with active='password' %}
        </div>
        <div class="col-md-9">
            <form role="form" class="form-horizontal" method="post" action="{% url 'userprofile:password' %}">
                {% csrf_token %}
                {{ form.id }}
                {% for field in form.visible_fields %}
                <div class="form-group{% if field.errors %} has-error{% endif %}">
                    <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-9">
                        {{ field }}
                        {% if field.help_text %}
                        <span class="help-block">{{ field.help_text }}</span>
                        {% endif %}
                        {% for error in field.errors %}
                        <label class="control-label">{{ error }}</label>
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-9">
                        <button type="submit" class="tg-btn">{% trans 'Save' %}</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
  </div>
</div>
{% endblock index %}

labslot/userprofile/templates/profile/picture.html
{% load staticfiles %}
{% load i18n static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/notification.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.Jcrop.min.css' %}">
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.Jcrop.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/picture.js' %}" type="text/javascript"></script>
<main>
    <div class="page-content">
        <div class="row">
            {% if uploaded_picture %}
            <form method="post" action="{% url 'userprofile:save_uploaded_picture' %}">
                {{form.as_p}}
                {% csrf_token %}
                <div class="modal fade" id="modal-upload-picture">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                <h4 class="modal-title">{% trans 'Crop Picture' %}</h4>
                            </div>
                            <div class="modal-body">
                                <div class="selected-picture">
                                    <p>{% trans 'Crop the profile picture and then click on the' %} <strong>{% trans 'Save Picture' %}</strong> {% trans 'button' %}</p>
                                    <img src="{% get_media_prefix %}profile_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                                    <input type="hidden" id="x" name="x" />
                                    <input type="hidden" id="y" name="y" />
                                    <input type="hidden" id="w" name="w" />
                                    <input type="hidden" id="h" name="h" />
                                </div>
                                <script type="text/javascript">
                                $(function() {
                                    $("#modal-upload-picture").modal();
                                    window.history.pushState("", "", "/settings/picture/");
                                });
                                </script>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                                <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </div><!-- /.page-content -->
    </section><!-- /section.signup-wrap -->
    </div>
</main>

labslot/userprofile/templates/profile/profile_navigation.html
% load staticfiles %}
{% load i18n %}
{% load humanize %}
<header>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse" id="menu">
              <ul class="nav navbar-nav">
                <li>
                  <a href="#" id="notifications" data-container="body" data-toggle="popover" data-placement="bottom" title="Notifications">
                    <span class="glyphicon glyphicon-bell"></span>
                  </a>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <a href="{% url 'profile' user.username %}">{{ user.profile.get_screen_name }}</a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><span class="badge pull-right" id="unread-count">0</span> Inbox</a></li>
                    <li><a href="{% url 'userprofile:profilesettings' %}">{% trans 'Account Settings' %}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'authentication:logout' %}">{% trans 'Log out' %}</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

labslot/userprofile/templates/profile/settings.html
{% extends 'home/base.html' %}
{% block index %}
  <div class="page-header" style="padding-top: 20px;">
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'profile/partial_settings_menu.html' with active='profile' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">Edit Profile</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'userprofile:profilesettings' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-2 control-label">{{ field.label }}</label>
            <div class="col-sm-10">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock%}

labslot/userprofile/templates/profile/user.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load i18n static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.Jcrop.min.css' %}">
{% block index %}
<div class="container">
    <div class="page-content" style="padding:30px">
        <div class="row">
            <div class="col-md-2">
                {% include 'profile/partial_settings_menu.html' with active='picture' %}
            </div>
            <div class="col-md-3">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                <img src="{{ user.profile.get_picture }}" style="width: 150px; border-radius: 5px; margin-bottom: 1em;">
                <form enctype="multipart/form-data" method="post" action="{% url 'userprofile:upload_picture' %}" id="picture-upload-form">
                    {% csrf_token %}
                    <input type="file" name="picture" style="display: none">
                    <button type="button" class="btn btn-default" id="btn-upload-picture">{% trans 'Upload new picture' %}</button>
                </form>
            </div>
            <div class="col-md-7">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="tg-btn">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

labslot/userprofile/templates/profile/userlist.html
{% load staticfiles %}
{% load i18n %}
{% include 'head.html' %}
{% include 'base.html' %}
{% load widget_tweaks %}
{% block main %}
<link href="{% static 'css/network.css' %}" rel="stylesheet" type="text/css">
<div class="page-header">
    <h1 style="text-align: center;">User-Lists</h1>
</div>
<div class="users">
    <div>
        {% for user in users %}
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <img src="{{ user.profile.get_picture }}" style="width:50px">
                    <a href="{% url 'profile' user.username %}">{{ user.profile.get_screen_name }}</a>
                </div>
                <div class="panel-body">
                    <p><strong>{% trans 'Job Title' %}:</strong> {{ user.profile.job_title }}</p>
                    <p><strong>{% trans 'Username' %}: </strong> {{ user.username }}</p>
                    <p><strong>{% trans 'Location' %}:</strong> {{ user.profile.location }}</p>
                    {% if user.profile.url %}
                    <p><strong>{% trans 'Url' %}:</strong> {{ user.profile.get_url }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}</div>
    <div class="row">{% endif %}
        {% endfor %}
    </div>
    {% endblock main %}
    </main>
    {% include 'footer.html' %}